---
 - name: Create ~/.aws/
   file:
     path: "/home/{{ ansible_user }}/.aws/"
     state: directory
     owner: "{{ ansible_user }}"
   tags:
     - aws
     - create-aws-dir

 - name: Upload credentials file
   template:
       src: credentials.j2
       dest: "/home/{{ ansible_user }}/.aws/credentials"
       owner: "{{ ansible_user }}"
       mode: 0600
   tags:
     - aws
     - upload-aws-creds
